[build-system]
  requires = ["setuptools>=64", "setuptools_scm>=8"]
  build-backend = "setuptools.build_meta"

[project]
  name = "jinjabread"
  description = "An Python-based static site generator using Jinja templates."
  dynamic = ["version"]
  requires-python = ">=3.9"
  readme = "README.md"
  license = {file = "LICENSE"}
  dependencies = [
    "jinja2==3.1.3",
    "markdown==3.6",
    "markdown-full-yaml-metadata==2.2.1",
    "beautifulsoup4==4.12.3",
    "werkzeug[watchdog]==3.0.1",
  ]

[project.urls]
  Repository = "https://github.com/jdeanwallace/jinjabread.git"
  Issues = "https://github.com/jdeanwallace/jinjabread/issues"

[tool.setuptools]
  packages = ["jinjabread"]

[tool.setuptools_scm]
